In [74]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [75]:
df = pd.read_csv(r"C:\pp\ml--2026\tsv\credit_card.csv")
df.head()

,gender,age,job,marital,education,default,housing,loan,contact,CreditCard
0,female,56,housemaid,married,basic.4y,no,no,no,telephone,no
1,male,57,services,married,high.school,yes,no,no,telephone,no
2,female,37,services,married,high.school,no,yes,no,telephone,no
3,female,40,admin.,married,basic.6y,no,no,no,telephone,no
4,female,56,services,married,high.school,no,no,yes,telephone,no

In [76]:
df.shape
df.describe()

               age
count  41188.00000
mean      40.02406
std       10.42125
min       17.00000
25%       32.00000
50%       38.00000
75%       47.00000
max       98.00000

# Q1: What is the Probability that the Customer has a Credit Card

In [77]:
#First find the total number of customer
S = df.shape[0]
print(S)

41188

In [78]:
has_credit = len(df[df["CreditCard"] == "yes"])
print(has_credit/S)

0.11265417111780131

# Q2: What is the Probability that the Customer age is greater than 50 ?

In [79]:
age_greater = len(df[df["age"]>50])
print(age_greater/S)

0.17432261823832185

# Q3: What is the probability that the customer is illiterate?

In [114]:
illiterate_customer = len(df[df["education"] == "Illiterate"])
print(illiterate_customer/S)

0.0

# Q4: What is the Probability that the Customer has a Telephone ?

In [81]:
has_telephone = len(df[df["contact"] == "telephone"])
print(has_telephone/S)

0.3652520151500437

# Q5: What is the Probability that the Customer is Single and has a Credit Card ?

In [82]:
single_and_has_creditCard = len( df[ (df["marital"] != "married") & (df["CreditCard"] == "yes") ] )
print(single_and_has_creditCard/S)

0.05117995532679421

# Q6: What is the Probability that the Customer is Male and has at most 6 Year of Education ?

In [83]:
male_and_6_education = len( df[ (df["gender"] == "male") & (df["education"] == "basic.6y") ] )
print(male_and_6_education/S)

0.027265222880450617

# Q7: What is the Probability that the Customer is Retired and is divorced ?

In [84]:
male_and_6_education = len( df[ (df["job"] == "retired") & (df["marital"] == "divorced") ] )
print(male_and_6_education/S)

0.008449062833835098

# Q8: Given the Customer has the credit card, find the probability that he/she is married ?

In [85]:
married_and_has_creditCard = len( df[ (df["marital"] == "married") & (df["CreditCard"] == "yes") ] )
print(married_and_has_creditCard/S)

0.06147421579100709

# Q9: If a customer has a management job, find the probability that he has a housing

In [86]:
managemnet_and_has_housing = len( df[ (df["job"] == "managemnet") & (df["housing"] == "yes") ] )
print(managemnet_and_has_housing/S)

0.0

# Part 2: Bayes Theorem

In [87]:
#Read and show file 'kerala_floods.csv'
df2 = pd.read_csv(r"C:\pp\ml--2026\tsv\kerala_floods.csv")
df2.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,YES
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,YES
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,YES
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,YES
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,NO

In [88]:
#Show the size
df2.shape
#Check if you have missing values
df2.isna().sum()

SUBDIVISION         0
YEAR                0
JAN                 0
FEB                 0
MAR                 0
APR                 0
MAY                 0
JUN                 0
JUL                 0
AUG                 0
SEP                 0
OCT                 0
NOV                 0
DEC                 0
 ANNUAL RAINFALL    0
FLOODS              0
dtype: int64

# We need to use Bays Therorm to calculate the probability of having a rainfall more than 500 mm in month of June, provided it has flooded in that year ?

# 1- We may start by preparing the required columns:

In [89]:
# create new column with the name "June_more_than_500" and assign 1 for more 500 and 0 for less 500
df2["June_more_than_500"] =  (df2['JUL']<500).astype('int') 

#Let us do the same with 'FLOODS' but assign 1 for yes and 0 for no
df2['FLOODS'] = df2['FLOODS'].map({"YES":1,"NO":0})

# 2- Select only the columns that will help to answer the main question.

In [90]:
df2[['YEAR',"June_more_than_500",'FLOODS']].head()

   YEAR  June_more_than_500  FLOODS
0  1901                   0       1
1  1902                   0       1
2  1903                   0       1
3  1904                   0       1
4  1905                   0       0

# 3- Create a cross tabulation for 'FLOODS' and 'June_more_than_500'

In [91]:
pd.crosstab(df2['FLOODS'],df2['June_more_than_500'],margins=True)

June_more_than_500   0   1  All
FLOODS
0                   39  19   58
1                   57   3   60
All                 96  22  118

# 4- What is the probability of a rainfall more than 500mm in June?

In [92]:
print(22/118)
#P(A)

0.1864406779661017

# 5- What is the probability of having a flood?

In [93]:
print(60/118)
#P(B)

0.5084745762711864

# 6- What is the probability of having a flood and a rainfall more than 500mm in June?

In [94]:
print(3/118)
#P(A and B) = P(A)*P(B)

0.025423728813559324

# 7- What is the Probability of having a flood given it rained more than 500mm in June?

In [95]:
print(3/22)
#P(B/A) = (P(A)*P(B))/P(A)

0.13636363636363635

# 8- What is the probability of a rainfall less than 500mm in June?

In [96]:
print(96/118)
#P(not A)

0.8135593220338984

# 9- What is probability of having a flood given that it rained less than 500mm?

In [97]:
print(57/96)
#P(B/ not A) = (P(B)*P(not A))/P(not A)

0.59375

Calculate the probability of having a rainfall more than 500mm in month of June, provided it has flooded
in that year ?

In [100]:
#P(A)/P(B) = P(A)*P(B_given_A)/P(B)
print((3*22)/60)

1.1

# 10- Answer this question by using Bayes Theorem and the law of the Total Probaility

In [105]:
P_A = 22 / 118
P_not_A = 96 / 118

# P(B|A) 
P_B_given_A = 3 / 22
# P(B|not A) 
P_B_given_not_A = 57 / 96

# Law of Total Probability for P(B) 
P_B_total = (P_B_given_A * P_A) + (P_B_given_not_A * P_not_A)

# Bayes Theorem
P_A_given_B = (P_B_given_A * P_A) / P_B_total

print(round(P_A_given_B, 2))

0.05

# 11- Answer this question by using Bayes Theorem only.

In [104]:
P_A = 22 / 118
P_B_given_A = 3 / 22
P_B = 60 / 118

# Bayes Theorem
P_A_given_B = (P_B_given_A * P_A) / P_B

print(round(P_A_given_B, 2))

0.05

In [107]:
pd.crosstab(df2['FLOODS'],df2['June_more_than_500'],margins=True)

June_more_than_500   0   1  All
FLOODS
0                   39  19   58
1                   57   3   60
All                 96  22  118